# Generated by Django 6.0.3 on 2026-04-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=25, verbose_name='Прізвище')),
                ('middle_name', models.CharField(max_length=25, null=True, verbose_name='По-батькові')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата народження')),
                ('date_of_death', models.DateField(null=True, verbose_name='Дата смерті')),
                ('description', models.TextField(verbose_name='Інформація')),
                ('photo_url', models.CharField(max_length=200, null=True, verbose_name='Посилання на фото')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Звання')),
                ('order', models.IntegerField(verbose_name='Цінність звання')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft', verbose_name='Борт')),
                ('aircrew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircrew.aircrew', verbose_name='Член екіпажу')),
            ],
        ),
        migrations.AddField(
            model_name='aircrew',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircrew.rank', verbose_name='Звання'),
        ),
    ]
