# Generated by Django 6.0.3 on 2026-04-01 14:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircrew',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='aircrew',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aircrew',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='aircrew',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерті'),
        ),
        migrations.AlterField(
            model_name='aircrew',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Інформація'),
        ),
        migrations.AlterField(
            model_name='aircrew',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='По-батькові'),
        ),
    ]
