# Generated by Django 6.0.3 on 2026-04-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва підрозділу')),
                ('military_unit_number', models.PositiveIntegerField(verbose_name='Номер військової частини')),
                ('dislocation', models.CharField(max_length=200, verbose_name='Місце дислокації')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HELICOPTER', 'Helicopter'), ('PLANE', 'Plane')], max_length=15, verbose_name='Тип')),
                ('tail_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Бортовий номер')),
                ('tail_color', models.CharField(blank=True, choices=[('BLUE', 'Blue'), ('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow')], max_length=10, null=True, verbose_name='Колір бортового номеру')),
                ('register_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Реєстрційний номер')),
                ('serial_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Серійний номер')),
                ('status', models.CharField(choices=[('DAMAGED', 'Damaged'), ('DESTROYED', 'Destroyed'), ('CAPTURED', 'Captured')], max_length=15, verbose_name='Статус')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Локація')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircraft.aircraftmodel', verbose_name='Модель')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircraft.subdivision', verbose_name='Підрозділ')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='URL посилання')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft')),
            ],
        ),
    ]
