# Generated by Django 6.0.3 on 2026-04-01 14:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftphoto',
            name='url',
        ),
        migrations.AddField(
            model_name='aircraftphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
