# Generated by Django 6.0.3 on 2026-04-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_remove_aircraftphoto_url_aircraftphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бортовий номер'),
        ),
    ]
