# Generated by Django 6.0.3 on 2026-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_alter_aircraft_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Бортовий номер'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='military_unit_number',
            field=models.CharField(max_length=10, verbose_name='Номер військової частини'),
        ),
    ]
