# Generated by Django 6.0.3 on 2026-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_alter_aircraft_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(choices=[('DAMAGED', 'Пошкоджений'), ('DESTROYED', 'Знищений'), ('CAPTURED', 'Захоплений')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail_color',
            field=models.CharField(blank=True, choices=[('BLUE', 'Синій'), ('RED', 'Червоний'), ('WHITE', 'Білий'), ('YELLOW', 'Жовтий')], max_length=10, null=True, verbose_name='Колір бортового номеру'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='type',
            field=models.CharField(blank=True, choices=[('HELICOPTER', 'Гелікоптер'), ('PLANE', 'Літак')], max_length=15, null=True, verbose_name='Тип'),
        ),
    ]
