# Generated by Django 6.0.3 on 2026-04-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_alter_aircraft_status_alter_aircraft_tail_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='type',
        ),
    ]
