# Generated by Django 6.0.3 on 2026-04-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0006_remove_aircraft_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('category', models.CharField(choices=[('PLANE', 'Літак'), ('HELICOPTER', 'Гелікоптер')], max_length=20, verbose_name='Категорія')),
            ],
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircraft.aircraftmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircraft.aircrafttype', verbose_name='Тип'),
        ),
    ]
